export * from '@/views/ErrorView';
export * from '@/views/HomeView';
export * from '@/views/movies/CreditsView';
export * from '@/views/movies/MovieView';
export * from '@/views/NowPlayingView';
export * from '@/views/movies/ReviewsView';
export * from '@/views/TrendingView';
export * from '@/views/SearchView';
export * from './movies/MoviesView'; 
